from sqlalchemy import Column, Integer, String, Boolean, DateTime, TIMESTAMP
from db import Base


class User(Base):
    __tablename__ = "user"
    id = Column(Integer, primary_key=True)
    username = Column(String(255), unique=True)
    password_hash = Column(String(255))
    auth_key = Column(String(32))
    status = Column(Integer)
    fullname = Column(String(255))
    filial_id = Column(Integer)
    maosh = Column(Integer)
    kpi = Column(Boolean)
    oylik = Column(Integer)
    role = Column(String(255))
    phone = Column(Integer)
    created_at = Column(Integer)
    updated_at = Column(Integer)
    balance = Column(Integer)
    moi_zvonki_user_name = Column(String(255))
    user_moi_zvonki_address = Column(String(255))
    user_moi_zvonki_api = Column(String(255))
    ozroq_kpi = Column(Boolean)
    plastik = Column(Integer)
    click = Column(Integer)
    phone2 = Column(String(15))
    zayavka_limit = Column(Integer)
    topshirish_limit = Column(Integer)
    skald_limit = Column(Integer)
    api_token = Column(String(255), default='')
    zakaz_status = Column(Integer)


class Costumers(Base):
    __tablename__ = "costumers"
    id = Column(Integer, primary_key=True)
    chat_id = Column(Integer)
    costumers_filial_id = Column(Integer)
    costumer_name = Column(String(255))
    costumer_phone_1 = Column(String(255))
    costumer_phone_2 = Column(String(255))
    costumer_phone_3 = Column(String(255))
    costumer_addres = Column(String(255))
    costumer_nationality = Column(String(255))
    costumer_date = Column(DateTime)
    costumer_source = Column(String(255))
    orienter = Column(String(255))
    costumer_status = Column(String(255))
    costumer_turi = Column(String(255))
    saygak_id = Column(Integer)
    mintaqa_id = Column(Integer)
    manba = Column(String(100))
    token = Column(String(100))
    parol = Column(String(100))
    user_id = Column(Integer)
    millat_id = Column(Integer)
    call_count = Column(Integer)
    calling = Column(Boolean)
    izoh = Column(String(255))
    created_at = Column(TIMESTAMP)
    updated_at = Column(TIMESTAMP)
